### ISSUE TITLE
Failed dependencies: python is needed by clustershell-1.6-1.el6.noarch

### ISSUE THREAD

**Issue by dzlab** [jbenninghoff/cluster-validation#4]
I'm having trouble when trying to setup (as root) the cluster validation tools on a Ubuntu x86_64. I'm also having the same problem on MapR M3 on AWS EMR.
```
$ rpm -i clustershell-1.6-1.el6.noarch.rpm
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: clustershell-1.6-1.el6.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
error: Failed dependencies:
        /usr/bin/python is needed by clustershell-1.6-1.el6.noarch
        python(abi) = 2.6 is needed by clustershell-1.6-1.el6.noarch
```
When I use the flag `--nodeps`, the installation succeed and the folder `/etc/clustershell/` is created but still have a problem:
```
$ clush -a date
Traceback (most recent call last):
  File "/usr/bin/clush", line 7, in <module>
    from ClusterShell.CLI.Clush import main
```  
Any idea what went wrong and how to fix it?

**Comment by dbtucker** [comment]
Clustershell is available from the Ubuntu core repositories, so there's no need to use rpm directly for installation on most Ubuntu systems.   Simply use
	sudo apt-get install clustershell

All the dependencies should be resolved properly.

**Comment by dzlab** [comment]
I still have a dependency problem on AWS (It worked for me on a local ubuntu machine):
```
$ uname -a
Linux ip-172-31-44-44.us-west-2.compute.internal 3.2.30-49.59.amzn1.x86_64 #1 SMP Wed Oct 3 19:54:33 UTC 2012 x86_64 GNU/Linux
$ sudo apt-get install clustershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clustershell : Depends: python (>= 2.6.6-7~) but 2.6.6-3+squeeze7 is to be installed
E: Broken packages
```

**Comment by jbenninghoff** [comment]
Is AWS using an older Ubuntu version?  Can you easily change/upgrade Ubuntu
version on AWS if possible?
How about a newer Ubuntu repository?
​

/John

**Comment by DLade** [comment]
It seems that on the AWS is Debian (Squeeze) and not Ubuntu installed - see https://packages.debian.org/squeeze/python-all-dev

With an update to a newer version of debian the problem should be solved - see https://packages.debian.org/wheezy/python-all-dev

If this is no option you may try to install a newer version of python (2.7) parallel to the current package - see http://stackoverflow.com/questions/5907352/installing-second-python-on-debian

HTH Danny

**Comment by shikharravi** [comment]
I am new to mapr in AWS and having same issue.. any idea how to  fix this.
[root@ip-10-0-0-15 MAPR]# rpm -i pre-install/clustershell-1.6-1.el6.noarch.rpm
warning: pre-install/clustershell-1.6-1.el6.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
error: Failed dependencies:
	python(abi) = 2.6 is needed by clustershell-1.6-1.el6.noarch
[root@ip-10-0-0-15 MAPR]# uname -a
Linux ip-10-0-0-15.us-west-2.compute.internal 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jbenninghoff** [comment]
Try using EPEL via yum.  That will handle dependencies better.

**Comment by shikharravi** [comment]
Thanks, i tried but did not worked.
[root@ip-10-0-0-1 ~]# wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
--2015-10-30 21:38:01--  http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 209.132.181.26, 209.132.181.23, 209.132.181.24, ...
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|209.132.181.26|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14524 (14K) [application/x-rpm]
Saving to: ‘epel-release-7-5.noarch.rpm’

100%[========================================================================================>] 14,524      --.-K/s   in 0.05s   

2015-10-30 21:38:01 (298 KB/s) - ‘epel-release-7-5.noarch.rpm’ saved [14524/14524]

[root@ip-10-0-0-1 ~]# rpm -ivh epel-release-7-5.noarch.rpm
warning: epel-release-7-5.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:epel-release-7-5                 ################################# [100%]
[root@ip-10-0-0-1 ~]# cd MAPR/
[root@ip-10-0-0-1 MAPR]# cd pre-install/
[root@ip-10-0-0-1 pre-install]# rpm -ivh clustershell-1.6-1.el6.noarch.rpm
warning: clustershell-1.6-1.el6.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
error: Failed dependencies:
	python(abi) = 2.6 is needed by clustershell-1.6-1.el6.noarch
[root@ip-10-0-0-1 pre-install]#

**Comment by jbenninghoff** [comment]
Now that you have EPEL installed and configured, you should be able to use
yum instead of rpm.
yum install cluster-shell
Can you try that?

**Comment by shikharravi** [comment]
Awesome , It worked..now i can proceed to the lab exercises :) Thank you!!

**Comment by shikharravi** [comment]
looks like i m missing something .. after i did try yum install.. it worked but did not created any extract or any thing installed.
[root@ip-10-0-0-1 pre-install]# yum install clustershell-1.6-1.el6.noarch.rpm 
Loaded plugins: amazon-id, rhui-lb
Examining clustershell-1.6-1.el6.noarch.rpm: clustershell-1.6-1.el6.noarch
Marking clustershell-1.6-1.el6.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package clustershell.noarch 0:1.6-1.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: clustershell-1.6-1.el6.noarch
--> Finished Dependency Resolution
Error: Package: clustershell-1.6-1.el6.noarch (/clustershell-1.6-1.el6.noarch)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-16.el7.x86_64 (@anaconda/7.1)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-18.el7_1.1.x86_64 (rhui-REGION-rhel-server-releases)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python34-3.4.3-2.el7.x86_64 (epel)
               python(abi) = 3.4
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by sid8074** [comment]
@shikharravi I am having the same issue..Did you find the solution?

**Comment by jbenninghoff** [comment]
Did you try the yum output suggestions like —skip-broken?
If you have 2.7.x Python, it should work.

/John Benninghoff

**Comment by sid8074** [comment]
root@ip-10-0-0-212:~# rpm -ivh epel-release-7-5.noarch.rpm 
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: epel-release-7-5.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
error: Failed dependencies:
	redhat-release >= 7 is needed by epel-release-7-5.noarch

**Comment by jbenninghoff** [comment]
Are you using the right version of EPEL that matches your version of RHEL or CentOS?
Looks like EPEL rpm is failing to install because of that.  This is a different issue than what shikharravi saw.

/John Benninghoff

**Comment by sid8074** [comment]
I am using ubuntu 14.04 in AWS..

**Comment by jbenninghoff** [comment]
Ubuntu doesn’t use EPEL.  They use another repository scheme and they don’t use yum either.
I use CentOS and RHEL, so I am not very familiar with Ubuntu.
I know from other users, Ubuntu has a repository that carries cluster-shell package.

/John Benninghoff

**Comment by sid8074** [comment]
I changed OS to RHEL 7.2...but still having the same issue

[root@ip-10-0-0-125 pre-install]# yum install clustershell-1.6-1.el6.noarch.rpm --skip-broken
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Examining clustershell-1.6-1.el6.noarch.rpm: clustershell-1.6-1.el6.noarch
Marking clustershell-1.6-1.el6.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package clustershell.noarch 0:1.6-1.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: clustershell-1.6-1.el6.noarch
Packages skipped because of dependency problems:
    clustershell-1.6-1.el6.noarch from /clustershell-1.6-1.el6.noarch

Before that I did yum update --skip-broken
Still I cant find the clustershell in etc directory.
I am doing MapR on demand training using AWS.
Please help so I can proceed furthur..
@jbenninghoff @shikharravi  thanks..

**Comment by jbenninghoff** [comment]
Do you have EPEL  for RHEL 7.2 configured?
If so, try "yum search clustershell".
If it doesn't find it, you may have to fall back to RHEL 6.x.

**Comment by sid8074** [comment]
It works on RHEL 6.5..Thanks @jbenninghoff

**Comment by vijittalwar** [comment]
Hi jbenninghoff and sid8074, I am also facing same issue and tried all the things mentioned above and getting same results as sid8074.  Only difference is I am not able to go back to RHEL 6.5 and using RHEL 7.2 only. The command "yum search clustershell" brings below results but I am unable to see any file at  /etc/clustershell/groups location. Even the folder clustershell is not created.-

_**[root@ip-10-0-0-60 ~]# yum search clustershell
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
========================== N/S matched: clustershell ===========================
vim-clustershell.noarch : VIM files for ClusterShell
clustershell.noarch : Python framework for efficient cluster administration

  Name and summary matches only, use "search all" for everything.
[root@ip-10-0-0-60 ~]#**_

**Comment by sid8074** [comment]
@vijittalwar You can not downgrade the OS..You need to install the RHEL 6.5 from AWS and follow the instructions as per lab guide..

**Comment by vijittalwar** [comment]
thx.  a lot 4 help. It worked by using RHEL 6.5.
